/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmosestructuras;

import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class EvaluacionDos extends javax.swing.JFrame {
    
    int matrizA[][];
    int matrizB[][];
    int matrizC[][];
    int matrizTC[][];
    int numeroMayor = 0;
    boolean band = false;
    
    /**
     * Creates new form EvaluacionDos
     */
    public EvaluacionDos() {
        initComponents();
        jBorrarButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jVarN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jVarM = new javax.swing.JTextField();
        jVarP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jVarO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMatrizC = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jMatrizTC = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jMatrizB = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jMatrizA = new javax.swing.JTextArea();
        jGenerarButton = new javax.swing.JButton();
        jBorrarButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jDeterminante = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jFibonacci = new javax.swing.JTextArea();
        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Variable N:");

        jVarN.setMinimumSize(new java.awt.Dimension(30, 20));
        jVarN.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel2.setText("Variable M:");

        jVarM.setMinimumSize(new java.awt.Dimension(30, 20));
        jVarM.setPreferredSize(new java.awt.Dimension(50, 25));

        jVarP.setMinimumSize(new java.awt.Dimension(30, 20));
        jVarP.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel3.setText("Variable P:");

        jVarO.setMinimumSize(new java.awt.Dimension(30, 20));
        jVarO.setPreferredSize(new java.awt.Dimension(50, 25));

        jLabel4.setText("Variable O:");

        jMatrizC.setEditable(false);
        jMatrizC.setColumns(20);
        jMatrizC.setRows(5);
        jMatrizC.setTabSize(7);
        jMatrizC.setFocusable(false);
        jScrollPane2.setViewportView(jMatrizC);

        jMatrizTC.setEditable(false);
        jMatrizTC.setColumns(20);
        jMatrizTC.setRows(5);
        jMatrizTC.setTabSize(7);
        jMatrizTC.setFocusable(false);
        jScrollPane3.setViewportView(jMatrizTC);

        jMatrizB.setEditable(false);
        jMatrizB.setColumns(20);
        jMatrizB.setRows(5);
        jMatrizB.setTabSize(7);
        jMatrizB.setFocusable(false);
        jScrollPane4.setViewportView(jMatrizB);

        jMatrizA.setEditable(false);
        jMatrizA.setColumns(20);
        jMatrizA.setRows(5);
        jMatrizA.setTabSize(7);
        jMatrizA.setFocusable(false);
        jScrollPane5.setViewportView(jMatrizA);

        jGenerarButton.setText("Generar");
        jGenerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerarButtonActionPerformed(evt);
            }
        });

        jBorrarButton.setText("Borrar");
        jBorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Matriz A:");

        jLabel6.setText("Matriz B:");

        jLabel7.setText("Matriz C (AxB):");

        jLabel8.setText("Matriz Traspuesta de C:");

        jDeterminante.setEditable(false);
        jDeterminante.setColumns(20);
        jDeterminante.setRows(1);
        jDeterminante.setTabSize(7);
        jDeterminante.setFocusable(false);
        jScrollPane6.setViewportView(jDeterminante);

        jLabel9.setText("Determinante");

        jLabel10.setText("Fibonacci");

        jFibonacci.setEditable(false);
        jFibonacci.setColumns(20);
        jFibonacci.setRows(1);
        jFibonacci.setTabSize(7);
        jFibonacci.setFocusable(false);
        jScrollPane7.setViewportView(jFibonacci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(163, 163, 163))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(643, 643, 643)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jVarN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jVarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jVarO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jVarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGenerarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBorrarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jVarO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGenerarButton)
                            .addComponent(jBorrarButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVarM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVarN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addGap(123, 123, 123)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGenerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerarButtonActionPerformed
        // TODO add your handling code here:
        jGenerarButton.setEnabled(false);
        jBorrarButton.setEnabled(true);
        
        jVarM.setEnabled(false);
        jVarN.setEnabled(false);
        jVarP.setEnabled(false);
        jVarO.setEnabled(false);
        
        int m = 0;
        int n = 0;
        int p = 0;
        int o = 0;
        
        try{
            m = Integer.parseInt(jVarM.getText());
            n = Integer.parseInt(jVarN.getText());
            p = Integer.parseInt(jVarP.getText());
            o = Integer.parseInt(jVarO.getText());
        } catch (Exception e){}                   
        
        if ( !(m >= 2 && m <=5) || !(n >= 2 && n <=5) || !(p >= 2 && p <=5) || !(o >= 2 && o <=5)){
            JOptionPane.showMessageDialog(this, "Debes de ingresar numeros entre 2 y 5");                                                
            return;
        }
        
        matrizA = new int[n][m];
        matrizB = new int[o][p];
        
        llenarMatriz(matrizA);
        llenarMatriz(matrizB);
        
        jMatrizA.setText(obtenerMatrizOrdenada(matrizA));
        jMatrizB.setText(obtenerMatrizOrdenada(matrizB));                
        
        if(m == o){
            matrizC = multiplicarMatriz(matrizA,matrizB);
            jMatrizC.setText(obtenerMatrizOrdenada(matrizC));       
            matrizTC = transversa(matrizC);
            jMatrizTC.setText(obtenerMatrizOrdenada(matrizTC));
        } else{            
            JOptionPane.showMessageDialog(this, "La matriz no se puede multiplicar");
        }
        
        
        jFibonacci.setText(fibonacci(numeroMayor));
    }//GEN-LAST:event_jGenerarButtonActionPerformed

    private int[][] multiplicarMatriz(int[][] a, int[][] b){
        int matriz[][] = new int[a.length][b[0].length];
        
        for (int i = 0; i < a.length; i++) {
            for (int j = 0; j < b[0].length; j++) {
                for (int k = 0; k < a[0].length; k++) {                    
                    matriz[i][j] += a[i][k] * b[k][j];
                }
            }
        }
        
        return matriz;
       
    }
    
    private int[][] transversa(int[][] a){
        int matriz[][] = new int[a[0].length][a.length];
        
        for (int i = 0; i< a.length; i++){
            for (int j = 0; j < a[0].length; j++){
                //System.out.println(String.format("%s %s", i,j));
                matriz[j][i] = a[i][j];
            }
        }
        
        return matriz;
    }
    
    private String obtenerMatrizOrdenada(int matriz[][]){
        String texto = "";
        for(int i = 0; i<matriz.length; i++){
            for (int j = 0; j<matriz[i].length; j++){
                // generar numero random de 2 a 4 dig                
                texto = texto + String.format("%6d", matriz[i][j]) + " ";
            }
            texto+="\n";
        }
        return texto;
    }
    
    private void llenarMatriz(int matriz[][]){
        for(int i = 0; i<matriz.length; i++){
            for (int j = 0; j<matriz[i].length; j++){
                // generar numero random de 2 a 4 dig
                
                matriz[i][j] = ThreadLocalRandom.current().nextInt(10,99);
                
                if (!band && matriz[i][j] > numeroMayor){
                    numeroMayor = matriz[i][j];
                }
            }
        }
        
        if (!band){
            band = true;            
        }
    }
    
    private String fibonacci(int n){               
      
        int t1 = 0, t2 = 1;        
        String str = "0  1";
                
        boolean ciclo = true;
        while(ciclo){
            int sum = t1 + t2;
            t1 = t2;
            t2 = sum;
            
            if(sum<numeroMayor){
                str += "  "+sum;
            } else {
                ciclo = false;
            }                        
        }
        
        return str;
    }
    
    private void jBorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarButtonActionPerformed
        
        jGenerarButton.setEnabled(true);
        jBorrarButton.setEnabled(false);
        
        jMatrizA.setText("");
        jMatrizB.setText(""); 
        jMatrizC.setText(""); 
        
        
        numeroMayor = 0;
        band = false;
        
        jVarM.setEnabled(true);
        jVarN.setEnabled(true);
        jVarP.setEnabled(true);
        jVarO.setEnabled(true);
        
        jVarM.setText("");
        jVarN.setText("");
        jVarP.setText("");
        jVarO.setText("");
        
        this.jFibonacci.setText("");
        this.jMatrizTC.setText("");
    }//GEN-LAST:event_jBorrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvaluacionDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvaluacionDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvaluacionDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvaluacionDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvaluacionDos().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBorrarButton;
    private javax.swing.JTextArea jDeterminante;
    private javax.swing.JTextArea jFibonacci;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton jGenerarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jMatrizA;
    private javax.swing.JTextArea jMatrizB;
    private javax.swing.JTextArea jMatrizC;
    private javax.swing.JTextArea jMatrizTC;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jVarM;
    private javax.swing.JTextField jVarN;
    private javax.swing.JTextField jVarO;
    private javax.swing.JTextField jVarP;
    // End of variables declaration//GEN-END:variables
}
