/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoritmosestructuras;

import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonny
 */
public class Matriz extends javax.swing.JFrame {

    int matriz[][];
    int vectorMayor[];
    int vectorMenor[];
    int diagonalPrincipal[];
    int tamano;
    int numeroMayor;
    int numeroMenor;
    int sumaDiagonalPrincipal;
    
    /**
     * Creates new form Matriz
     */
    public Matriz() {
        initComponents();
        jBorrarButton.setEnabled(false);
    }
    
    private void generarMatriz(int n){
        matriz = new int[n][n];
        vectorMayor = new int[n*n];        
        diagonalPrincipal = new int[n];
        String texto = "";
        int pos = 0;
        
        for(int i = 0; i<matriz.length; i++){
            for (int j = 0; j<matriz[i].length; j++){
                // generar numero random de 2 a 4 dig
                matriz[i][j] = ThreadLocalRandom.current().nextInt(10,9999);
                texto = texto + String.format("%6d", matriz[i][j]) + " ";
                
                //Crear vector con elementos de la matriz
                vectorMayor[pos] = matriz[i][j];
                
                //calcular numero mayor
                if (pos == 0){
                    numeroMayor = matriz[i][j];
                    numeroMenor = matriz[i][j];
                }
                
                if (matriz[i][j] > numeroMayor){
                    numeroMayor = matriz[i][j];
                }
                
                if (matriz[i][j] < numeroMenor){
                    numeroMenor = matriz[i][j];
                }
                
                // Ayuda a generar vector de elementos
                pos+=1;
                
                //Llenado de vector diagonal principal
                if (i==j){
                    diagonalPrincipal[i] = matriz[i][j];
                    sumaDiagonalPrincipal += diagonalPrincipal[i];
                    System.out.println(diagonalPrincipal[i]);
                }                                
            }
            texto += "\n";
        }
        
        jMatrizTextArea.setText(texto);
        
        // Calcular vectores mayor a menor y menor a mayor
        texto = "";
        vectorMenor = vectorMayor;
        vectorMenor = Utilitarios.ordenarVector(vectorMenor);
        for (int i = 0; i < vectorMayor.length; i++){
            texto = texto + String.format("%6d", vectorMenor[i]) + " ";
        }
        jVectorMenorMatrizTextArea.setText(texto);
        
        texto = "";
        vectorMayor = vectorMenor;
        vectorMayor = Utilitarios.ordenarVectorMayorAMenor(vectorMayor);
        for (int i = 0; i < vectorMayor.length; i++){
            texto = texto + String.format("%6d", vectorMayor[i]) + " ";
        }
        jVectorMayorMatrizTextArea.setText(texto);
        
        // Numero mayor y menor de la matriz
        jNumeroMayorLabel.setText(numeroMayor+"");
        jNumeroMenorLabel.setText(numeroMenor+"");
        
        //Diagonal principal suma
        jSumaDiagonalPrincipalLabel.setText(sumaDiagonalPrincipal+"");
        
        // suma digitos numeromayor
        int sumaDigitos = 0;
        String aux = Integer.toString(numeroMayor);
        for(int i=0; i<aux.length(); i++){
            sumaDigitos +=  Character.getNumericValue(aux.charAt(i));      
        }
        jSumaNumeroMayorLabel.setText(sumaDigitos+"");
        
    }

    private void inactivarBotones(){
        jNumeroTextField.setEnabled(false);
        jGenerarButton.setEnabled(false);
        jBorrarButton.setEnabled(false);        
    }
    
    private void activarBotones(){
        jNumeroTextField.setEnabled(true);
        jGenerarButton.setEnabled(true);               
    }
    
    private void limpiarFormulario(){
        activarBotones();
        jBorrarButton.setEnabled(false);
        jNumeroTextField.setText("");
        
        jMatrizTextArea.setText("");
        jVectorMenorMatrizTextArea.setText("");
        jVectorMayorMatrizTextArea.setText("");
        
        // Numero mayor y menor de la matriz
        jNumeroMayorLabel.setText("");
        jNumeroMenorLabel.setText("");
        
        
        jSumaDiagonalPrincipalLabel.setText("");
        
        jSumaNumeroMayorLabel.setText("");
        
        tamano = 0;
        numeroMayor = 0;
        numeroMenor = 0;
        sumaDiagonalPrincipal = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMatrizTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jNumeroTextField = new javax.swing.JTextField();
        jGenerarButton = new javax.swing.JButton();
        jBorrarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jVectorMayorMatrizTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jVectorMenorMatrizTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jNumeroMayorLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jNumeroMenorLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSumaDiagonalPrincipalLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSumaNumeroMayorLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMatrizTextArea.setEditable(false);
        jMatrizTextArea.setColumns(20);
        jMatrizTextArea.setRows(5);
        jMatrizTextArea.setTabSize(7);
        jMatrizTextArea.setFocusable(false);
        jScrollPane2.setViewportView(jMatrizTextArea);

        jLabel1.setText("Matriz");

        jLabel2.setText("Ingresa un numero");

        jNumeroTextField.setMinimumSize(new java.awt.Dimension(40, 30));
        jNumeroTextField.setPreferredSize(new java.awt.Dimension(40, 30));

        jGenerarButton.setText("Generar");
        jGenerarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerarButtonActionPerformed(evt);
            }
        });

        jBorrarButton.setText("Borrar");
        jBorrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Vector Elementos Matriz Mayor a Menor");

        jLabel4.setText("Vector Elementos Matriz Menor a Mayor");

        jVectorMayorMatrizTextArea.setEditable(false);
        jVectorMayorMatrizTextArea.setColumns(20);
        jVectorMayorMatrizTextArea.setRows(1);
        jVectorMayorMatrizTextArea.setTabSize(7);
        jVectorMayorMatrizTextArea.setFocusable(false);
        jScrollPane3.setViewportView(jVectorMayorMatrizTextArea);

        jVectorMenorMatrizTextArea.setEditable(false);
        jVectorMenorMatrizTextArea.setColumns(20);
        jVectorMenorMatrizTextArea.setRows(1);
        jVectorMenorMatrizTextArea.setTabSize(7);
        jVectorMenorMatrizTextArea.setFocusable(false);
        jScrollPane4.setViewportView(jVectorMenorMatrizTextArea);

        jLabel5.setText("El numero mayor es: ");

        jNumeroMayorLabel.setText("-------");

        jLabel7.setText("El numero menor es: ");

        jNumeroMenorLabel.setText("-------");

        jLabel8.setText("Suma elementos Diag Principal:");

        jSumaDiagonalPrincipalLabel.setText("-------");

        jLabel9.setText("Suma digitos numero mayor:");

        jSumaNumeroMayorLabel.setText("-------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGenerarButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSumaDiagonalPrincipalLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNumeroMenorLabel))
                            .addComponent(jBorrarButton)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jNumeroMayorLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSumaNumeroMayorLabel)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jGenerarButton)
                    .addComponent(jNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBorrarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jNumeroMayorLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jNumeroMenorLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jSumaDiagonalPrincipalLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jSumaNumeroMayorLabel))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jGenerarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerarButtonActionPerformed
        // TODO add your handling code here:        
        if(jNumeroTextField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes de ingresar un numero");
        } else {
            tamano = 0;
            try {
                tamano = Integer.parseInt(jNumeroTextField.getText());                
            } catch(Exception e){                                                
            }            
            
            if (tamano <= 0){
                JOptionPane.showMessageDialog(this, "Debes de ingresar un numero valido");                                                
                jNumeroTextField.setText("");
            }
            else {
                jNumeroTextField.setEnabled(false);
                jGenerarButton.setEnabled(false);
                jBorrarButton.setEnabled(true);
                generarMatriz(tamano);
                
            }            
        }
    }//GEN-LAST:event_jGenerarButtonActionPerformed

    private void jBorrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarButtonActionPerformed

        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_jBorrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matriz().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBorrarButton;
    private javax.swing.JButton jGenerarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jMatrizTextArea;
    private javax.swing.JLabel jNumeroMayorLabel;
    private javax.swing.JLabel jNumeroMenorLabel;
    private javax.swing.JTextField jNumeroTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jSumaDiagonalPrincipalLabel;
    private javax.swing.JLabel jSumaNumeroMayorLabel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jVectorMayorMatrizTextArea;
    private javax.swing.JTextArea jVectorMenorMatrizTextArea;
    // End of variables declaration//GEN-END:variables
}
